version: '3.9'

services:
    mariadb:
        image: mariadb
        build: ./requirements/mariadb
        container_name: mariadb
        restart: always
        volumes:
            - db:/var/lib/mysql
        networks:
            - inception
        init: true
    nginx:
        depends_on:
            - wordpress
        image: nginx
        build: ./requirements/nginx
        container_name: nginx
        restart: always
        ports:
            - "443:443"
        volumes:
            - data:/var/www/wordpress
        networks:
            - inception
        init: true
    wordpress:
        depends_on:
            - mariadb
        image: wordpress
        build: ./requirements/wordpress
        container_name: wordpress
        restart: always
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_HOST=${MYSQL_HOST}
        volumes:
            - data:/var/www/wordpress
        networks:
            - inception
        init: true

volumes:
    data:
        name: data
        driver: local
        driver_opts:
            device: ${VOLUMES_DATA_PATH}
            o: bind
            type: volume
    db:
        name: db
        driver: local
        driver_opts:
            device: ${VOLUMES_DB_PATH}
            o: bind
            type: volume

networks:
    inception:
        driver: bridge