services:
  mariadb:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    # command: '--default-authentication-plugin=mysql_native_password'
    # volumes:
    #   - db_data:/var/lib/mysql
    restart: always
    # environment:
    #   - MYSQL_ROOT_PASSWORD=somewordpress
    #   - MYSQL_DATABASE=wordpress
    #   - MYSQL_USER=wordpress
    #   - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
    networks:
      - intra
    tty: true
  wordpress:
    image: wordpress:latest
    expose:
      - 9000
    restart: always
    volumes:
      - data:/var/www/html
    # environment:
    #   - WORDPRESS_DB_HOST=db
    #   - WORDPRESS_DB_USER=wordpress
    #   - WORDPRESS_DB_PASSWORD=wordpress
    #   - WORDPRESS_DB_NAME=wordpress
    networks:
      - intra
    tty: true
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 443:443
    volumes:
      - data:/var/www/html
    networks:
      - intra
    tty: true
  networks:
    intra:
      driver: bridge
# volumes:
#   db_data: