FROM debian:buster

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get -y install \
	mariadb-client \
	php7.3 \
	php-fpm \
	php-cli \
	wget \
	curl \
	php-mysql \
	php-mbstring \
	php-xml \
	sendmail



